import { MovementTest } from '../types';

export const movementTests: MovementTest[] = [
  { id: 1, name: 'Mandibular depression', description: 'פתיחת הפה כלפי מטה', rangeNote: 'הערת טווח: הכנסת 3 אצבעות לפה', oppositeAction: 'בדיקת השרירים המעלים את עצם הלסת' },
  { id: 2, name: 'Mandibular protraction', description: 'דחיפת הלסת קדימה', rangeNote: 'הערה: תנועה קדמית של השיניים התחתונות', oppositeAction: 'בדיקת השרירים המושכים את עצם הלסת אחורה' },
  { id: 3, name: 'Head rotation', description: 'סיבוב הראש ימינה ושמאלה', rangeNote: 'הערת טווח: 70–90°', oppositeAction: 'בדיקת השרירים המסובבים את הראש לכיוון הנגדי' },
  { id: 4, name: 'Head flexion', description: 'כפיפת הראש קדימה, סנטר לכיוון בית החזה', rangeNote: 'הערת טווח: 60°', oppositeAction: 'בדיקת השרירים המיישרים את הגולגולת ואת עמוד השדרה' },
  { id: 5, name: 'Head extension', description: 'הטיית הראש לאחור', rangeNote: 'הערת טווח: 50°', oppositeAction: 'בדיקת השרירים המכופפים את הגולגולת ואת עמוד השדרה' },
  { id: 6, name: 'Head side/lateral flexion', description: 'הטיית הראש, אוזן לכיוון כתף', rangeNote: 'הערת טווח: 45°', oppositeAction: 'בדיקת השרירים המחזירים למרכז ומתנגדים להטיה' },
  { id: 7, name: 'Shoulder joint flexion', description: 'הרמת הזרוע קדימה ולמעלה', rangeNote: 'הערת טווח: 180°', oppositeAction: 'בדיקת השרירים הפושטים את הכתף' },
  { id: 8, name: 'Shoulder joint extension', description: 'לקיחת הזרוע לאחור', rangeNote: 'הערת טווח: 45–60°', oppositeAction: 'בדיקת השרירים המכופפים את הכתף' },
  { id: 9, name: 'Shoulder joint abduction & external rotation / adduction', description: 'רמת הזרוע הצידה תוך כדי סיבובה החוצה, כך שהאגודל פונה לאחור.', rangeNote: 'הערה: בדיקה משולבת', oppositeAction: 'עבור הרחקה: בדיקת המקרבים; עבור קירוב: בדיקת המרחיקים' },
  { id: 10, name: 'Shoulder joint internal rotation & abduction / external rotation & adduction', description: 'הרמת הזרוע הצידה תוך כדי סיבובה פנימה, כך שהאגודל פונה קדימה.', rangeNote: 'הערה: דפוסי תנועה משולבים', oppositeAction: 'לפי הדפוס הנגדי: מסובבים החוצה מול מסובבים פנימה, מרחיקים מול מקרבים' },
  { id: 11, name: 'Shoulder joint adduction', description: 'קירוב הזרוע אל הגוף', rangeNote: 'הערת טווח: 30°', oppositeAction: 'בדיקת השרירים המרחיקים את הכתף' },
  { id: 12, name: 'Shoulder joint horizontal abduction', description: 'הרחקה אופקית לאחור', rangeNote: 'הערת טווח: 45°', oppositeAction: 'בדיקת השרירים לקירוב אופקי' },
  { id: 13, name: 'Shoulder joint horizontal adduction', description: 'קירוב אופקי קדימה', rangeNote: 'הערת טווח: 45°', oppositeAction: 'בדיקת השרירים להרחקה אופקית' },
  { id: 14, name: 'Scapula elevation', description: 'הרמת הכתפיים והשכמות למעלה', rangeNote: 'הערת טווח: שכמות בקו האוזן', oppositeAction: 'בדיקת השרירים המורידים את השכמות' },
  { id: 15, name: 'Scapula protraction', description: 'הרחקת השכמות זו מזו, דחיפה קדימה', rangeNote: 'הערת טווח: 45° כשמרפק מסובב פנימה', oppositeAction: 'בדיקת השרירים המקרבים את השכמות לעמוד השדרה ‎(retraction)' },
  { id: 16, name: 'Scapula retraction', description: 'קירוב השכמות לעמוד השדרה', rangeNote: 'הערת טווח: 30° כשזרוע בסיבוב פנימי', oppositeAction: 'בדיקת השרירים המרחקים את השכמות ‎(protraction)' },
  { id: 17, name: 'Scapula protraction', description: 'דחיפת שכמות קדימה', rangeNote: 'הערת טווח: 45° כשזרוע בסיבוב חיצוני', oppositeAction: 'בדיקת השרירים לקירוב השכמות' },
  { id: 18, name: 'Scapula retraction', description: 'קירוב שכמות', rangeNote: 'הערת טווח: 20° כשזרוע בסיבוב חיצוני', oppositeAction: 'בדיקת השרירים להרחקת שכמות' },
  { id: 19, name: 'Elbow flexion', description: 'כפיפת המרפק', rangeNote: 'הערת טווח: 80°', oppositeAction: 'בדיקת השרירים הפושטים את המרפק' },
  { id: 20, name: 'Elbow extension', description: 'יישור המרפק', rangeNote: 'הערת טווח: 170°', oppositeAction: 'בדיקת השרירים המכופפים את המרפק' },
  { id: 21, name: 'Elbow supination', description: 'סיבוב האמה כך שהכף פונה מעלה', rangeNote: 'הערת טווח: 80°', oppositeAction: 'בדיקת השרירים לפרונציה' },
  { id: 22, name: 'Elbow pronation', description: 'סיבוב האמה כך שהכף פונה מטה', rangeNote: 'הערת טווח: 80°', oppositeAction: 'בדיקת השרירים לסופינציה' },
  { id: 23, name: 'Wrist flexion in pronation', description: 'כפיפת שורש כף היד כשכף היד פונה מטה', rangeNote: '', oppositeAction: 'בדיקת השרירים הפושטים את שורש כף היד' },
  { id: 24, name: 'Wrist extension in pronation', description: 'יישור שורש כף היד כשכף היד פונה מטה', rangeNote: '', oppositeAction: 'בדיקת השרירים המכופפים את שורש כף היד' },
  { id: 25, name: 'Wrist flexion in supination', description: 'כפיפה כשכף היד פונה מעלה', rangeNote: '', oppositeAction: 'בדיקת השרירים הפושטים את שורש כף היד' },
  { id: 26, name: 'Wrist extension in supination', description: 'יישור כשכף היד פונה מעלה', rangeNote: '', oppositeAction: 'בדיקת השרירים המכופפים את שורש כף היד' },
  { id: 27, name: 'Wrist radial deviation', description: 'הטיה לכיוון האגודל', rangeNote: 'הערת טווח: 20°', oppositeAction: 'בדיקת השרירים להטיה אולנרית' },
  { id: 28, name: 'Wrist ulnar deviation (adduction)', description: 'הטיה לכיוון הזרת', rangeNote: 'הערת טווח: 30°', oppositeAction: 'בדיקת השרירים להטיה רדיאלית' },
  { id: 29, name: 'Pollicis flexion', description: 'כפיפת האגודל', rangeNote: 'הערת טווח: 70–90°', oppositeAction: 'בדיקת השרירים המיישרים את האגודל' },
  { id: 30, name: 'Pollicis extension', description: 'יישור האגודל', rangeNote: 'הערת טווח: 30°', oppositeAction: 'בדיקת השרירים המכופפים את האגודל' },
  { id: 31, name: 'Pollicis abduction', description: 'הרחקת האגודל מהכף', rangeNote: 'הערת טווח: 45°', oppositeAction: 'בדיקת השרירים לקירוב האגודל' },
  { id: 32, name: 'Pollicis adduction', description: 'קירוב האגודל אל כף היד', rangeNote: '', oppositeAction: 'בדיקת השרירים להרחקת האגודל' },
  { id: 33, name: 'Pollicis opposition', description: 'הבאת האגודל אל הזרת, מגע כריות', rangeNote: '', oppositeAction: 'בדיקת השרירים לריפוזיציה ‎(החזרה מקו האופוזיציה)' },
  { id: 34, name: 'Fist', description: 'אגרוף מלא, סגירת כל האצבעות', rangeNote: '', oppositeAction: 'בדיקת פתיחת אצבעות ופשיטת שורש כף היד' },
  { id: 35, name: 'Lumbar – Pelvis elevation & Hip IR/ER', description: 'הרמת אגן וסיבוב ירך פנימה או החוצה בעמידה', rangeNote: '', oppositeAction: 'הפעולה ההפוכה בהתאם: הורדת אגן, סיבוב נגדי של הירך' },
  { id: 36, name: 'Lumbar flexion', description: 'כיפוף גב קדימה', rangeNote: 'הערת טווח שכיח: להגיע עם הידיים לכפות הרגליים', oppositeAction: 'בדיקת פשיטת עמוד השדרה המותני' },
  { id: 37, name: 'Lumbar rotation', description: 'סיבוב גו לימין או לשמאל', rangeNote: '', oppositeAction: 'בדיקת הסיבוב הנגדי וייצוב גו' },
  { id: 38, name: 'Lumbar side flexion/bending', description: 'הטיית גו לצד', rangeNote: 'הערת טווח: 25°, להגיע עם אצבעות עד מרכז הברך', oppositeAction: 'בדיקת הטיה לצד הנגדי' },
  { id: 39, name: 'Hip flexion (כפיפת ירך)', description: 'הרמת הרגל כולה קדימה, כך שהירך מתקרבת לכיוון הבטן.', rangeNote: 'הערת טווח בעמידה: 90–100°', oppositeAction: 'בדיקת פשיטת הירך' },
  { id: 40, name: 'Hip extension (פשיטת ירך)', description: 'לקיחת הרגל כולה לאחור. תנועה זו מוגבלת יותר מכפיפה.', rangeNote: 'הערת טווח בעמידה: 45–60°', oppositeAction: 'בדיקת כפיפת הירך' },
  { id: 41, name: 'Hip abduction (הרחקת ירך)', description: 'הרחקת הרגל הצידה, הרחק מקו האמצע של הגוף.', rangeNote: 'הערת טווח בעמידה: 45°', oppositeAction: 'בדיקת קירוב הירך' },
  { id: 42, name: 'Hip adduction (קירוב ירך)', description: 'קירוב הרגל חזרה לקו האמצע של הגוף. תנועה זו מתבצעת בדרך כלל לאחר הרחקה.', rangeNote: 'הערת טווח בעמידה: 30°', oppositeAction: 'בדיקת הרחקת הירך' },
  { id: 43, name: 'Hip horizontal abduction (הרחקה אופקית)', description: 'תנועה מורכבת יותר, המבוצעת לרוב כשהירך נמצאת בכפיפה של 90 מעלות. בתנועה זו, מרחיקים את הירך לצד במנח אופקי.', rangeNote: 'הערת טווח בעמידה: 45–60°', oppositeAction: 'בדיקת קירוב אופקי של הירך' },
  { id: 44, name: 'Hip IR when flexed (Internal Rotation - סיבוב פנימי)', description: 'כשהברך והירך כפופות, הרגל התחתונה זזה החוצה מהגוף.', rangeNote: 'הערת טווח: 15°', oppositeAction: 'בדיקת סיבוב חיצוני (ER)' },
  { id: 45, name: 'Hip ER when flexed (External Rotation - סיבוב חיצוני)', description: 'כשהברך והירך כפופות, הרגל התחתונה זזה פנימה לכיוון הגוף.', rangeNote: 'הערת טווח: 45°', oppositeAction: 'בדיקת סיבוב פנימי (IR)' },
  { id: 46, name: 'Knee flexion (כפיפת ברך)', description: 'כיפוף הברך, כך שהעקב מתקרב לישבן. תנועה זו היא ההפך מפשיטת ברך (יישור הברך).', rangeNote: 'הערת טווח: 90–135°', oppositeAction: 'בדיקת יישור הברך' },
  { id: 47, name: 'Knee extension', description: 'יישור ברך', rangeNote: 'הערה: יישור מלא עם “Snap” קל בסוף טווח', oppositeAction: 'בדיקת כפיפת הברך' },
  { id: 48, name: 'Knee Internal & External rotation when the knee is flexed', description: 'סיבוב שוקה פנימה וחוצה כשהברך בכפיפה', rangeNote: 'הערת טווח: 25° לכל כיוון', oppositeAction: 'פעולה הפוכה לפי הכיוון הנגדי' },
  { id: 49, name: 'Ankle dorsi flexion', description: 'כפיפה גבית של הקרסול, ברך קדימה מעל כף הרגל', rangeNote: 'הערת טווח: 20°', oppositeAction: 'בדיקת כפיפה כפית של הקרסול' },
  { id: 50, name: 'Ankle plantar flexion (point)', description: 'פוינט, דחיפה מטה', rangeNote: 'הערת טווח: 40°', oppositeAction: 'בדיקת כפיפה גבית' },
  { id: 51, name: 'Ankle inversion', description: 'היפוך פנימי של הקרסול', rangeNote: 'הערת טווח: 30°', oppositeAction: 'בדיקת היפוך חיצוני ‎(eversion)' },
  { id: 52, name: 'Ankle eversion', description: 'היפוך חיצוני', rangeNote: 'הערת טווח: 20°', oppositeAction: 'בדיקת היפוך פנימי ‎(inversion)' },
  { id: 53, name: 'Hallucis flexion', description: 'כפיפת הבוהן הגדולה', rangeNote: 'הערת טווח: 15°', oppositeAction: 'בדיקת יישור הבוהן הגדולה' },
  { id: 54, name: 'Hallucis extension', description: 'יישור הבוהן הגדולה', rangeNote: 'הערת טווח: 60°', oppositeAction: 'בדיקת כפיפת הבוהן הגדולה' },
];